// build.rs
//
// 构建脚本：
// 1. 调用 tauri_build 构建 Tauri 应用
// 2. 在测试模式下自动生成测试代码

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // 始终调用 tauri_build
    tauri_build::build();

    // 配置重新运行条件
    println!("cargo:rerun-if-changed=src/bin/ifai/tests/suite");
    println!("cargo:rerun-if-changed=src/bin/ifai/tests/generate_tests.rs");

    // 检测并行测试配置
    let parallel_tests = std::env::var("IFAI_PARALLEL_TESTS")
        .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
        .unwrap_or(false);

    // 始终生成测试代码（不管是否在测试模式）
    // 因为 build.rs 在编译库时运行，而不是在编译测试时运行
    println!("cargo:warning=正在生成测试代码...");
    if parallel_tests {
        println!("cargo:warning=⚡️ 并行测试模式已启用");
    }

    if let Err(e) = generate_tests(parallel_tests) {
        println!("cargo:warning=测试生成失败: {}", e);
        println!("cargo:warning=提示: 运行 `cargo run --bin generate_tests` 手动生成");
    } else {
        println!("cargo:warning=测试代码生成完成");
    }
}

/// 生成所有测试
fn generate_tests(parallel_tests: bool) -> Result<(), Box<dyn std::error::Error>> {
    let base_dir = Path::new("src/bin/ifai/tests");
    let suite_dir = base_dir.join("suite");
    let generated_dir = base_dir.join("generated");

    // 检查 suite 目录是否存在
    if !suite_dir.exists() {
        println!("cargo:warning=⚠️  测试套件目录不存在: {:?}", suite_dir);
        return Ok(());
    }

    // 创建生成目录
    fs::create_dir_all(&generated_dir)?;

    // 处理每个 YAML 测试套件
    let mut generated_count = 0;
    for entry in fs::read_dir(&suite_dir)? {
        let entry = entry?;
        let path = entry.path();

        if path.extension().and_then(|s| s.to_str()) == Some("yaml") ||
           path.extension().and_then(|s| s.to_str()) == Some("yml") {
            println!("cargo:warning=📄 正在处理: {:?}", path.file_name().unwrap());

            // 读取 YAML 内容
            let yaml_content = fs::read_to_string(&path)?;

            // 解析 YAML
            let schema: serde_yaml::Value = serde_yaml::from_str(&yaml_content)
                .map_err(|e| format!("解析 YAML 失败: {} - {:?}", e, path))?;

            // 生成 Rust 测试代码（传递并行模式）
            let test_code = generate_test_from_schema(&schema, &path, parallel_tests)?;

            // 写入生成的测试文件（跳过已存在的手动维护文件）
            let file_name = path.file_stem()
                .and_then(|s| s.to_str())
                .ok_or("Invalid file name")?;
            let output_path = generated_dir.join(format!("{}.rs", file_name));
            if output_path.exists() {
                println!("cargo:warning=⏭️  跳过已存在: {:?}", output_path.file_name().unwrap());
            } else {
                fs::write(&output_path, test_code)?;
                generated_count += 1;
            }
        }
    }

    // 生成 mod.rs 以导出所有测试
    generate_mod_rs(&generated_dir)?;

    println!("cargo:warning=✨ 生成 {} 个测试文件", generated_count);

    Ok(())
}

/// 从 Schema 生成测试代码
fn generate_test_from_schema(
    schema: &serde_yaml::Value,
    yaml_path: &Path,
    parallel_tests: bool,
) -> Result<String, Box<dyn std::error::Error>> {
    let suite = schema.get("test_suite")
        .ok_or("Missing test_suite")?;

    let name = suite.get("name")
        .and_then(|v| v.as_str())
        .unwrap_or("Unknown");

    let tests = suite.get("tests")
        .and_then(|v| v.as_sequence())
        .ok_or("Missing tests")?;

    let mut code = String::new();

    // 文件头
    code.push_str("// Generated by build.rs\n");
    code.push_str("// DO NOT EDIT MANUALLY\n");
    code.push_str("// Original source: tests/suite\n");
    code.push_str(&format!("// Suite: {}\n", name));
    if parallel_tests {
        code.push_str("// Parallel test execution enabled\n");
    }
    code.push_str("\n");

    // 导入
    code.push_str("use crate::tests::common::*;\n\n");

    // 生成每个测试（跟踪函数名避免重复）
    let mut used_names = std::collections::HashSet::new();
    for test in tests {
        if let Some(test_code) = generate_single_test(test, &mut used_names, parallel_tests) {
            code.push_str(&test_code);
            code.push_str("\n");
        }
    }

    Ok(code)
}

/// 生成单个测试函数（支持参数化测试）
fn generate_single_test(
    test: &serde_yaml::Value,
    used_names: &mut std::collections::HashSet<String>,
    parallel_tests: bool,
) -> Option<String> {
    // 检查是否有参数化测试
    if let Some(_parameters) = test.get("parameters") {
        // 参数化测试：返回所有生成的测试代码（作为一个字符串）
        let param_tests = generate_parametrized_tests(test, used_names, parallel_tests);
        if !param_tests.is_empty() {
            return Some(param_tests.join("\n"));
        }
    }

    let name = test.get("name")?.as_str()?;
    let description = test.get("description").and_then(|v| v.as_str());

    // 提取标签
    let tags = extract_tags(test);

    // 使用拼音或数字ID来避免中文字符
    let mut test_name = to_test_name(name);

    // 如果函数名重复，添加序号后缀
    if used_names.contains(&test_name) {
        let mut counter = 2;
        loop {
            let unique_name = format!("{}_{}", test_name, counter);
            if !used_names.contains(&unique_name) {
                test_name = unique_name;
                break;
            }
            counter += 1;
        }
    }
    used_names.insert(test_name.clone());

    let mut code = String::new();

    code.push_str("#[tokio::test]\n");
    // 只在非并行模式下添加 serial_test::serial
    if !parallel_tests {
        code.push_str("#[serial_test::serial]\n");
    }
    code.push_str(&format!("async fn test_{}() {{\n", test_name));

    // 添加标签注释（用于测试脚本识别）
    if !tags.is_empty() {
        code.push_str(&format!("    // tags: {}\n", tags.join(", ")));
    }

    if let Some(desc) = description {
        code.push_str(&format!("    // {}\n", desc));
    }

    // 检查是否需要 Mock（覆盖所有 when 中的 mock 相关键）
    let needs_mock = test.get("when")
        .map(|w| when_needs_mock(w))
        .unwrap_or(false);

    if let Some(given) = test.get("given") {
        code.push_str(&generate_given(given, needs_mock, &[]));
    }

    // 从 given 中获取 args
    let args = test.get("given")
        .and_then(|g| g.get("args"))
        .and_then(|a| a.as_sequence());

    if let Some(when) = test.get("when") {
        code.push_str(&generate_when(when, args, needs_mock, &[]));
    } else if args.is_some() {
        // 没有 when 段但有 given.args，仍需生成 run_cli
        let args_vec: Vec<String> = args.unwrap().iter()
            .filter_map(|a| a.as_str())
            .map(|a| format!("\"{}\"", a.escape_default()))
            .collect();
        code.push_str(&format!("    let output = env.run_cli(&[{}]).await.unwrap();\n",
            args_vec.join(", ")));
    }

    if let Some(then) = test.get("then") {
        code.push_str(&generate_then(then, &[]));
    }

    code.push_str("}\n");
    Some(code)
}

/// 生成 Given 阶段
fn generate_given(given: &serde_yaml::Value, needs_mock: bool, params: &[(String, String)]) -> String {
    let mut code = String::new();

    if needs_mock {
        code.push_str("    let mut env = TestEnv::with_mock().await.unwrap();\n");
    } else {
        code.push_str("    let mut env = TestEnv::new().await.unwrap();\n");
    }

    if let Some(env_vars) = given.get("env") {
        if let Some(mapping) = env_vars.as_mapping() {
            for (key, value) in mapping {
                if let (Some(k), Some(v)) = (key.as_str(), value.as_str()) {
                    let substituted_value = substitute_variables(v, params);
                    code.push_str(&format!("    env.set_env(\"{}\", \"{}\");\n", k, substituted_value));
                }
            }
        }
    }

    if let Some(config) = given.get("config") {
        if let Some(config_str) = config.as_str() {
            let substituted_config = substitute_variables(config_str, params);
            code.push_str(&format!("    env.write_config(\"{}\").await.unwrap();\n",
                substituted_config.escape_default()));
        }
    }

    // 支持 stdin 输入
    if let Some(stdin) = given.get("stdin") {
        if let Some(stdin_str) = stdin.as_str() {
            let substituted_stdin = substitute_variables(stdin_str, params);
            code.push_str(&format!("    env.set_stdin(\"{}\");\n",
                substituted_stdin.escape_default()));
        }
    }

    // 支持 stdin_lines（多行 stdin 输入，用换行符拼接）
    if let Some(lines) = given.get("stdin_lines") {
        if let Some(lines_seq) = lines.as_sequence() {
            let combined: Vec<String> = lines_seq.iter()
                .filter_map(|l| l.as_str())
                .map(|l| substitute_variables(l, params))
                .collect();
            if !combined.is_empty() {
                code.push_str(&format!("    env.set_stdin(\"{}\");\n",
                    combined.join("\\n").escape_default()));
            }
        }
    }

    code
}

/// 判断 when 段是否需要 Mock 服务器
fn when_needs_mock(when: &serde_yaml::Value) -> bool {
    let mock_keys = [
        "mock_response",
        "mock_streaming",
        "mock_sse_streaming",
        "mock_sse_streaming_large",
        "mock_sse_streaming_slow",
        "mock_error_response",
        "mock_network_error",
        "mock_timeout",
        "mock_malformed_response",
        "mock_tool_call",
        "mock_tool_calls",
        "mock_tool_error",
        "mock_tool_timeout",
        "mock_compression",
        "mock_stdin_error",
        "setup_bad_config",
    ];
    mock_keys.iter().any(|k| when.get(*k).is_some())
}

/// 生成 When 阶段
fn generate_when(when: &serde_yaml::Value, given_args: Option<&serde_yaml::Sequence>, needs_mock: bool, params: &[(String, String)]) -> String {
    let mut code = String::new();

    // Mock 设置——声明式：从 when 中提取流式 chunk 并统一设置
    if needs_mock {
        code.push_str("    if let Some(mock) = env.mock_server() {\n");

        // mock_error_response: 模拟 API 返回错误（HTTP 4xx/5xx）
        if let Some(err) = when.get("mock_error_response") {
            let err_type = err.get("type").and_then(|v| v.as_str()).unwrap_or("error");
            let err_msg = err.get("message").and_then(|v| v.as_str()).unwrap_or("Error");
            let status = match err_type {
                "authentication_error" => 401,
                "rate_limit_error" => 429,
                "invalid_request_error" => 400,
                _ => 500,
            };
            let msg = substitute_variables(err_msg, params);
            code.push_str(&format!("        mock.setup_error_response({}, \"{}\").await.unwrap();\n",
                status, msg.escape_default()));
        }
        // mock_network_error: 模拟连接失败
        else if when.get("mock_network_error").is_some() {
            code.push_str("        mock.setup_network_error().await.unwrap();\n");
        }
        // mock_timeout: 模拟超时
        else if when.get("mock_timeout").is_some() || when.get("mock_sse_streaming_slow").is_some() {
            code.push_str("        mock.setup_timeout_response().await.unwrap();\n");
        }
        // mock_malformed_response: 模拟畸形 JSON
        else if let Some(raw) = when.get("mock_malformed_response").and_then(|v| v.as_str()) {
            let raw = substitute_variables(raw, params);
            code.push_str(&format!("        mock.setup_raw_response(\"{}\").await.unwrap();\n",
                raw.escape_default()));
        }
        // mock_response: 简单 JSON 响应
        else if let Some(resp) = when.get("mock_response").and_then(|v| v.as_str()) {
            let resp = substitute_variables(resp, params);
            code.push_str(&format!("        mock.setup_simple_response(\"{}\").await.unwrap();\n",
                resp.escape_default()));
        }
        // mock_stdin_error: stdin 读取错误（不需要 mock server 设置）
        else if when.get("mock_stdin_error").is_some() {
            // 不需要 mock server 设置
        }
        // 其他所有类型（mock_streaming, mock_sse_streaming, mock_tool_call, mock_tool_calls,
        // mock_compression, mock_sse_streaming_large, mock_tool_error, mock_tool_timeout）
        // 统一使用流式响应
        else {
            let chunks = extract_streaming_chunks(when, params);
            if chunks.is_empty() {
                code.push_str("        mock.setup_streaming_response(vec![\"Response\"]).await.unwrap();\n");
            } else {
                code.push_str(&format!("        mock.setup_streaming_response(vec![{}]).await.unwrap();\n",
                    chunks.join(", ")));
            }
        }

        code.push_str("    }\n");
    }

    // 优先使用 given 中的 args，其次使用 when 中的 args，最后使用默认值
    let args = given_args
        .or(when.get("args").and_then(|v| v.as_sequence()))
        .map(|v| v.iter()
             .filter_map(|a| a.as_str())
             .map(|a| {
                 let substituted = substitute_variables(a, params);
                 format!("\"{}\"", substituted.escape_default())
             })
             .collect::<Vec<_>>())
        .unwrap_or_else(|| vec!["\"hello\"".to_string()]);

    code.push_str(&format!("    let output = env.run_cli(&[{}]).await.unwrap();\n",
        args.join(", ")));

    code
}

/// 从 when 中提取流式 chunk 文本（统一处理 mock_streaming 和 mock_sse_streaming）
fn extract_streaming_chunks(when: &serde_yaml::Value, params: &[(String, String)]) -> Vec<String> {
    let chunks_seq = when.get("mock_streaming")
        .or(when.get("mock_sse_streaming"))
        .and_then(|v| v.as_sequence());

    if let Some(chunks) = chunks_seq {
        chunks.iter()
            .filter_map(|c| c.as_str())
            .map(|c| format!("\"{}\"", substitute_variables(c, params).escape_default()))
            .collect()
    } else {
        Vec::new()
    }
}

/// 生成 Then 阶段
fn generate_then(then: &serde_yaml::Value, params: &[(String, String)]) -> String {
    let mut code = String::new();

    // 处理 assert_success
    if let Some(success) = then.get("assert_success").and_then(|v| v.as_bool()) {
        if success {
            code.push_str("    output.assert_success();\n");
        } else {
            code.push_str("    assert!(!output.status.success(), \"Expected command to fail but it succeeded\\nstdout: {}\\nstderr: {}\", output.stdout, output.stderr);\n");
        }
    }

    if let Some(text) = then.get("assert_contains").and_then(|v| v.as_str()) {
        let substituted_text = substitute_variables(text, params);
        code.push_str(&format!("    output.assert_contains(\"{}\");\n",
            substituted_text.escape_default()));
    }

    if let Some(pattern) = then.get("assert_match").and_then(|v| v.as_str()) {
        let substituted_pattern = substitute_variables(pattern, params);
        code.push_str(&format!("    output.assert_match(r\"{}\");\n",
            substituted_pattern.escape_default()));
    }

    if let Some(tool) = then.get("assert_tool_called").and_then(|v| v.as_str()) {
        code.push_str(&format!("    output.assert_tool_called(\"{}\");\n",
            tool.escape_default()));
    }

    if let Some(count) = then.get("assert_token_count").and_then(|v| v.as_u64()) {
        code.push_str(&format!("    output.assert_token_count({});\n", count));
    }

    if then.get("assert_compression_triggered").and_then(|v| v.as_bool()).unwrap_or(false) {
        code.push_str("    output.assert_compression_triggered();\n");
    }

    code
}

/// 生成 mod.rs
fn generate_mod_rs(generated_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let mut mod_content = String::new();
    mod_content.push_str("// Generated by build.rs\n");
    mod_content.push_str("// DO NOT EDIT MANUALLY\n\n");

    for entry in fs::read_dir(generated_dir)? {
        let entry = entry?;
        let path = entry.path();

        if path.extension().and_then(|s| s.to_str()) == Some("rs") {
            if let Some(name) = path.file_stem().and_then(|s| s.to_str()) {
                if name != "mod" {
                    mod_content.push_str(&format!("pub mod {};\n", name));
                }
            }
        }
    }

    fs::write(generated_dir.join("mod.rs"), mod_content)?;

    Ok(())
}

/// 将测试名称转换为有效的 Rust 标识符
fn to_test_name(name: &str) -> String {
    // 扩展的拼音映射
    let pinyin_map: std::collections::HashMap<&str, &str> = [
        ("简单", "jian_dan"),
        ("提示词", "ti_shi_ci"),
        ("响应", "xiang_ying"),
        ("系统", "xi_tong"),
        ("生效", "sheng_xiao"),
        ("帮助", "bang_zhu"),
        ("信息", "xin_xi"),
        ("显示", "xian_shi"),
        ("版本", "ban_ben"),
        ("压缩", "ya_suo"),
        ("触发", "chu_fa"),
        ("保留", "bao_liu"),
        ("上下文", "shang_xia_wen"),
        ("工具", "gong_ju"),
        ("调用", "diao_yong"),
        ("长", "chang"),
        ("对话", "dui_hua"),
        ("自动", "zi_dong"),
        ("清理", "qing_li"),
        ("历史", "li_shi"),
        ("需要", "xu_yao"),
        ("审批", "shen_pi"),
        ("安全", "an_quan"),
        ("危险", "wei_xian"),
        ("手动", "shou_dong"),
        ("失败", "shi_bai"),
        ("执行", "zhi_xing"),
        ("后", "hou"),
        ("继续", "ji_xu"),
        ("禁用", "jin_yong"),
        ("模式", "mo_shi"),
        ("超时", "chao_shi"),
        ("管道", "guan_dao"),
        ("命令", "ming_ling"),
        ("多重", "duo_zhong"),
        ("依赖", "yi_lai"),
        ("单个", "dan_ge"),
        ("多个", "duo_ge"),
        ("删除", "shan_chu"),
        ("文件", "wen_jian"),
        ("处理", "chu_li"),
        ("完整", "wan_zheng"),
        ("流式", "liu_shi"),
        ("空", "kong"),
        ("网络", "wang_luo"),
        ("错误", "cuo_wu"),
        ("配置", "pei_zhi"),
        ("优先级", "you_xian_ji"),
        ("环境变量", "huan_jing_bian_liang"),
        ("读写", "du_xie"),
        ("中断", "zhong_duan"),
        ("累积", "ji_lei"),
        ("文本", "wen_ben"),
        ("增量", "zeng_liang"),
        ("跟踪", "gen_zong"),
        ("计数", "ji_shu"),
        ("恢复", "hui_fu"),
        ("传输", "chuan_shu"),
        ("速率", "su_lv"),
        ("限制", "zhi_xian"),
        ("多段", "duo_duan"),
        ("段落", "duan_luo"),
        ("代码", "dai_ma"),
        ("块", "kuai"),
    ].iter().cloned().collect();

    let mut result = name.to_string();

    // 替换所有已知的中文字符
    for (chinese, pinyin) in &pinyin_map {
        result = result.replace(chinese, pinyin);
    }

    // 移除剩余的非 ASCII 字符
    let result: String = result.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else if c.is_whitespace() || c == '-' || c == '/' {
                '_'
            } else {
                '_'
            }
        })
        .collect();

    // 清理连续的下划线
    let result = result.split('_')
        .filter(|s| !s.is_empty())
        .collect::<Vec<&str>>()
        .join("_");

    // 如果结果为空或全是数字，添加前缀
    if result.is_empty() || result.chars().all(|c| c.is_numeric()) {
        let hash = name.chars().map(|c| c as u32).sum::<u32>();
        format!("test_{:x}", hash)
    } else {
        result
    }
}

// ============================================================================
// 参数化测试支持
// ============================================================================

/// 参数值结构
#[derive(Debug, Clone)]
struct ParameterValue {
    name: String,
    values: Vec<String>,
}

/// 从测试中提取参数
fn extract_parameters(test: &serde_yaml::Value) -> Vec<ParameterValue> {
    let mut params = Vec::new();
    
    if let Some(parameters) = test.get("parameters") {
        if let Some(mapping) = parameters.as_mapping() {
            for (key, values) in mapping {
                if let (Some(name), Some(value_list)) = (key.as_str(), values.as_sequence()) {
                    let string_values: Vec<String> = value_list
                        .iter()
                        .filter_map(|v| v.as_str())
                        .map(|s| s.to_string())
                        .collect();
                    
                    if !string_values.is_empty() {
                        params.push(ParameterValue {
                            name: name.to_string(),
                            values: string_values,
                        });
                    }
                }
            }
        }
    }
    
    params
}

/// 生成参数组合（笛卡尔积）
fn generate_parameter_combinations(parameters: &[ParameterValue]) -> Vec<Vec<(String, String)>> {
    if parameters.is_empty() {
        return Vec::new();
    }
    
    let mut combinations = Vec::new();
    let mut current = Vec::new();
    generate_combinations_recursive(&parameters, 0, &mut current, &mut combinations);
    combinations
}

/// 递归生成参数组合
fn generate_combinations_recursive(
    parameters: &[ParameterValue],
    index: usize,
    current: &mut Vec<(String, String)>,
    combinations: &mut Vec<Vec<(String, String)>>,
) {
    if index >= parameters.len() {
        combinations.push(current.clone());
        return;
    }
    
    let param = &parameters[index];
    for value in &param.values {
        current.push((param.name.clone(), value.clone()));
        generate_combinations_recursive(parameters, index + 1, current, combinations);
        current.pop();
    }
}

/// 替换字符串中的变量占位符
fn substitute_variables(text: &str, params: &[(String, String)]) -> String {
    let mut result = text.to_string();
    for (name, value) in params {
        // 匹配 ${{name}} 格式（2个花括号）
        let placeholder = String::from("${{") + name + "}}";
        result = result.replace(&placeholder, value);
    }
    result
}

/// 在 YAML 值中替换变量
fn substitute_yaml_value(value: &serde_yaml::Value, params: &[(String, String)]) -> serde_yaml::Value {
    match value {
        serde_yaml::Value::String(s) => {
            serde_yaml::Value::String(substitute_variables(s, params))
        }
        serde_yaml::Value::Sequence(seq) => {
            serde_yaml::Value::Sequence(
                seq.iter()
                    .map(|v| substitute_yaml_value(v, params))
                    .collect()
            )
        }
        serde_yaml::Value::Mapping(map) => {
            let mut new_map = serde_yaml::Mapping::new();
            for (k, v) in map {
                new_map.insert(k.clone(), substitute_yaml_value(v, params));
            }
            serde_yaml::Value::Mapping(new_map)
        }
        _ => value.clone(),
    }
}

/// 生成参数化测试
fn generate_parametrized_tests(
    test: &serde_yaml::Value,
    used_names: &mut std::collections::HashSet<String>,
    parallel_tests: bool,
) -> Vec<String> {
    let parameters = extract_parameters(test);
    if parameters.is_empty() {
        return Vec::new();
    }

    let combinations = generate_parameter_combinations(&parameters);
    let mut tests = Vec::new();

    let base_name = test.get("name")
        .and_then(|v| v.as_str())
        .unwrap_or("parametrized_test");

    let base_description = test.get("description")
        .and_then(|v| v.as_str());

    for params in &combinations {
        // 创建参数化的测试副本
        let param_test = substitute_yaml_value(test, params);

        // 生成包含参数的测试名称
        let param_suffix: Vec<String> = params
            .iter()
            .map(|(name, value)| {
                let simple_value = value.replace(|c: char| !c.is_alphanumeric(), "_");
                format!("{}_{}", to_test_name(name), simple_value)
            })
            .collect();

        let full_test_name = format!("{}_{}",
            to_test_name(base_name),
            param_suffix.join("_")
        );

        // 确保函数名唯一
        let mut test_name = full_test_name.clone();
        let mut counter = 2;
        while used_names.contains(&test_name) {
            test_name = format!("{}_{}", full_test_name, counter);
            counter += 1;
        }
        used_names.insert(test_name.clone());

        // 生成测试代码（传递并行模式）
        let test_code = generate_single_test_from_yaml(&param_test, &test_name, base_description, params, parallel_tests);
        tests.push(test_code);
    }

    tests
}

/// 从 YAML 值生成单个测试代码（用于参数化测试）
fn generate_single_test_from_yaml(
    test: &serde_yaml::Value,
    test_name: &str,
    base_description: Option<&str>,
    params: &[(String, String)],
    parallel_tests: bool,
) -> String {
    let mut code = String::new();

    code.push_str("#[tokio::test]\n");
    // 只在非并行模式下添加 serial_test::serial
    if !parallel_tests {
        code.push_str("#[serial_test::serial]\n");
    }
    code.push_str(&format!("async fn test_{}() {{\n", test_name));

    // 提取标签
    let tags = extract_tags(test);

    // 添加标签注释（用于测试脚本识别）
    if !tags.is_empty() {
        code.push_str(&format!("    // tags: {}\n", tags.join(", ")));
    }

    // 添加参数说明注释
    if !params.is_empty() {
        code.push_str("    // 参数化测试:\n");
        for (name, value) in params {
            code.push_str(&format!("    //   {} = {}\n", name, value));
        }
    }

    // 添加描述
    if let Some(desc) = base_description {
        let desc_with_params = substitute_variables(desc, params);
        code.push_str(&format!("    // {}\n", desc_with_params));
    } else if let Some(desc) = test.get("description").and_then(|v| v.as_str()) {
        let desc_with_params = substitute_variables(desc, params);
        code.push_str(&format!("    // {}\n", desc_with_params));
    }
    
    // 检查是否需要 Mock（覆盖所有 when 中的 mock 相关键）
    let needs_mock = test.get("when")
        .map(|w| when_needs_mock(w))
        .unwrap_or(false);

    if let Some(given) = test.get("given") {
        code.push_str(&generate_given(&given, needs_mock, params));
    }

    let args = test.get("given")
        .and_then(|g| g.get("args"))
        .and_then(|a| a.as_sequence());

    if let Some(when) = test.get("when") {
        code.push_str(&generate_when(&when, args, needs_mock, params));
    } else if args.is_some() {
        // 没有 when 段但有 given.args，仍需生成 run_cli
        let args_vec: Vec<String> = args.unwrap().iter()
            .filter_map(|a| a.as_str())
            .map(|a| {
                let substituted = substitute_variables(a, params);
                format!("\"{}\"", substituted.escape_default())
            })
            .collect();
        code.push_str(&format!("    let output = env.run_cli(&[{}]).await.unwrap();\n",
            args_vec.join(", ")));
    }

    if let Some(then) = test.get("then") {
        code.push_str(&generate_then(&then, params));
    }
    
    code.push_str("}\n");
    code
}

// ============================================================================
// 测试标签系统
// ============================================================================

/// 从测试中提取标签
fn extract_tags(test: &serde_yaml::Value) -> Vec<String> {
    let mut tags = Vec::new();

    if let Some(tags_value) = test.get("tags") {
        if let Some(tags_seq) = tags_value.as_sequence() {
            for tag in tags_seq {
                if let Some(tag_str) = tag.as_str() {
                    tags.push(tag_str.to_string());
                }
            }
        } else if let Some(tag_str) = tags_value.as_str() {
            // 单个标签（字符串）
            tags.push(tag_str.to_string());
        }
    }

    tags
}
