// build.rs
//
// 构建脚本：
// 1. 调用 tauri_build 构建 Tauri 应用
// 2. 在测试模式下自动生成测试代码

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // 始终调用 tauri_build
    tauri_build::build();

    // 配置重新运行条件
    println!("cargo:rerun-if-changed=src/bin/ifai/tests/suite");
    println!("cargo:rerun-if-changed=src/bin/ifai/tests/generate_tests.rs");

    // 始终生成测试代码（不管是否在测试模式）
    // 因为 build.rs 在编译库时运行，而不是在编译测试时运行
    println!("cargo:warning=正在生成测试代码...");

    if let Err(e) = generate_tests() {
        println!("cargo:warning=测试生成失败: {}", e);
        println!("cargo:warning=提示: 运行 `cargo run --bin generate_tests` 手动生成");
    } else {
        println!("cargo:warning=测试代码生成完成");
    }
}

/// 生成所有测试
fn generate_tests() -> Result<(), Box<dyn std::error::Error>> {
    let base_dir = Path::new("src/bin/ifai/tests");
    let suite_dir = base_dir.join("suite");
    let generated_dir = base_dir.join("generated");

    // 检查 suite 目录是否存在
    if !suite_dir.exists() {
        println!("cargo:warning=⚠️  测试套件目录不存在: {:?}", suite_dir);
        return Ok(());
    }

    // 创建生成目录
    fs::create_dir_all(&generated_dir)?;

    // 处理每个 YAML 测试套件
    let mut generated_count = 0;
    for entry in fs::read_dir(&suite_dir)? {
        let entry = entry?;
        let path = entry.path();

        if path.extension().and_then(|s| s.to_str()) == Some("yaml") ||
           path.extension().and_then(|s| s.to_str()) == Some("yml") {
            println!("cargo:warning=📄 正在处理: {:?}", path.file_name().unwrap());

            // 读取 YAML 内容
            let yaml_content = fs::read_to_string(&path)?;

            // 解析 YAML
            let schema: serde_yaml::Value = serde_yaml::from_str(&yaml_content)
                .map_err(|e| format!("解析 YAML 失败: {} - {:?}", e, path))?;

            // 生成 Rust 测试代码
            let test_code = generate_test_from_schema(&schema, &path)?;

            // 写入生成的测试文件
            let file_name = path.file_stem()
                .and_then(|s| s.to_str())
                .ok_or("Invalid file name")?;
            let output_path = generated_dir.join(format!("{}.rs", file_name));
            fs::write(&output_path, test_code)?;
            generated_count += 1;
        }
    }

    // 生成 mod.rs 以导出所有测试
    generate_mod_rs(&generated_dir)?;

    println!("cargo:warning=✨ 生成 {} 个测试文件", generated_count);

    Ok(())
}

/// 从 Schema 生成测试代码
fn generate_test_from_schema(
    schema: &serde_yaml::Value,
    yaml_path: &Path,
) -> Result<String, Box<dyn std::error::Error>> {
    let suite = schema.get("test_suite")
        .ok_or("Missing test_suite")?;

    let name = suite.get("name")
        .and_then(|v| v.as_str())
        .unwrap_or("Unknown");

    let tests = suite.get("tests")
        .and_then(|v| v.as_sequence())
        .ok_or("Missing tests")?;

    let mut code = String::new();

    // 文件头
    code.push_str("// Generated by build.rs\n");
    code.push_str("// DO NOT EDIT MANUALLY\n");
    code.push_str("// Original source: tests/suite\n");
    code.push_str(&format!("// Suite: {}\n\n", name));

    // 导入
    code.push_str("use crate::tests::common::*;\n\n");

    // 生成每个测试（跟踪函数名避免重复）
    let mut used_names = std::collections::HashSet::new();
    for test in tests {
        if let Some(test_code) = generate_single_test(test, &mut used_names) {
            code.push_str(&test_code);
            code.push_str("\n");
        }
    }

    Ok(code)
}

/// 生成单个测试函数
fn generate_single_test(
    test: &serde_yaml::Value,
    used_names: &mut std::collections::HashSet<String>
) -> Option<String> {
    let name = test.get("name")?.as_str()?;
    let description = test.get("description").and_then(|v| v.as_str());

    // 使用拼音或数字ID来避免中文字符
    let mut test_name = to_test_name(name);

    // 如果函数名重复，添加序号后缀
    if used_names.contains(&test_name) {
        let mut counter = 2;
        loop {
            let unique_name = format!("{}_{}", test_name, counter);
            if !used_names.contains(&unique_name) {
                test_name = unique_name;
                break;
            }
            counter += 1;
        }
    }
    used_names.insert(test_name.clone());

    let mut code = String::new();

    code.push_str("#[tokio::test]\n");
    code.push_str("#[serial_test::serial]\n");
    code.push_str(&format!("async fn test_{}() {{\n", test_name));

    if let Some(desc) = description {
        code.push_str(&format!("    // {}\n", desc));
    }

    // 检查是否需要 Mock
    let needs_mock = test.get("when")
        .and_then(|w| w.get("mock_response"))
        .is_some()
        || test.get("when")
        .and_then(|w| w.get("mock_streaming"))
        .is_some();

    if let Some(given) = test.get("given") {
        code.push_str(&generate_given(given, needs_mock));
    }

    // 从 given 中获取 args
    let args = test.get("given")
        .and_then(|g| g.get("args"))
        .and_then(|a| a.as_sequence());

    if let Some(when) = test.get("when") {
        code.push_str(&generate_when(when, args, needs_mock));
    }

    if let Some(then) = test.get("then") {
        code.push_str(&generate_then(then));
    }

    code.push_str("}\n");
    Some(code)
}

/// 生成 Given 阶段
fn generate_given(given: &serde_yaml::Value, needs_mock: bool) -> String {
    let mut code = String::new();

    if needs_mock {
        code.push_str("    let mut env = TestEnv::with_mock().await.unwrap();\n");
    } else {
        code.push_str("    let mut env = TestEnv::new().await.unwrap();\n");
    }

    if let Some(env_vars) = given.get("env") {
        if let Some(mapping) = env_vars.as_mapping() {
            for (key, value) in mapping {
                if let (Some(k), Some(v)) = (key.as_str(), value.as_str()) {
                    code.push_str(&format!("    env.set_env(\"{}\", \"{}\");\n", k, v));
                }
            }
        }
    }

    if let Some(config) = given.get("config") {
        if let Some(config_str) = config.as_str() {
            code.push_str(&format!("    env.write_config(\"{}\").await.unwrap();\n",
                config_str.escape_default()));
        }
    }

    // 支持 stdin 输入
    if let Some(stdin) = given.get("stdin") {
        if let Some(stdin_str) = stdin.as_str() {
            code.push_str(&format!("    env.set_stdin(\"{}\");\n",
                stdin_str.escape_default()));
        }
    }

    code
}

/// 生成 When 阶段
fn generate_when(when: &serde_yaml::Value, given_args: Option<&serde_yaml::Sequence>, needs_mock: bool) -> String {
    let mut code = String::new();

    // Mock 设置
    if needs_mock {
        if when.get("mock_response").is_some() || when.get("mock_streaming").is_some() {
            code.push_str("    if let Some(mock) = env.mock_server() {\n");
            code.push_str("        mock.setup_streaming_response(vec![\"Response\"]).await.unwrap();\n");
            code.push_str("    }\n");
        }
    }

    // 优先使用 given 中的 args，其次使用 when 中的 args，最后使用默认值
    let args = given_args
        .or(when.get("args").and_then(|v| v.as_sequence()))
        .map(|v| v.iter()
             .filter_map(|a| a.as_str())
             .map(|a| format!("\"{}\"", a.escape_default()))
             .collect::<Vec<_>>())
        .unwrap_or_else(|| vec!["\"hello\"".to_string()]);

    code.push_str(&format!("    let output = env.run_cli(&[{}]).await.unwrap();\n",
        args.join(", ")));

    code
}

/// 生成 Then 阶段
fn generate_then(then: &serde_yaml::Value) -> String {
    let mut code = String::new();

    // 处理 assert_success
    if let Some(success) = then.get("assert_success").and_then(|v| v.as_bool()) {
        if success {
            code.push_str("    output.assert_success();\n");
        }
    }

    if let Some(text) = then.get("assert_contains").and_then(|v| v.as_str()) {
        code.push_str(&format!("    output.assert_contains(\"{}\");\n",
            text.escape_default()));
    }

    if let Some(pattern) = then.get("assert_match").and_then(|v| v.as_str()) {
        code.push_str(&format!("    output.assert_match(r\"{}\");\n",
            pattern.escape_default()));
    }

    if let Some(tool) = then.get("assert_tool_called").and_then(|v| v.as_str()) {
        code.push_str(&format!("    output.assert_tool_called(\"{}\");\n",
            tool.escape_default()));
    }

    if let Some(count) = then.get("assert_token_count").and_then(|v| v.as_u64()) {
        code.push_str(&format!("    output.assert_token_count({});\n", count));
    }

    if then.get("assert_compression_triggered").and_then(|v| v.as_bool()).unwrap_or(false) {
        code.push_str("    output.assert_compression_triggered();\n");
    }

    code
}

/// 生成 mod.rs
fn generate_mod_rs(generated_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let mut mod_content = String::new();
    mod_content.push_str("// Generated by build.rs\n");
    mod_content.push_str("// DO NOT EDIT MANUALLY\n\n");

    for entry in fs::read_dir(generated_dir)? {
        let entry = entry?;
        let path = entry.path();

        if path.extension().and_then(|s| s.to_str()) == Some("rs") {
            if let Some(name) = path.file_stem().and_then(|s| s.to_str()) {
                if name != "mod" {
                    mod_content.push_str(&format!("pub mod {};\n", name));
                }
            }
        }
    }

    fs::write(generated_dir.join("mod.rs"), mod_content)?;

    Ok(())
}

/// 将测试名称转换为有效的 Rust 标识符
fn to_test_name(name: &str) -> String {
    // 扩展的拼音映射
    let pinyin_map: std::collections::HashMap<&str, &str> = [
        ("简单", "jian_dan"),
        ("提示词", "ti_shi_ci"),
        ("响应", "xiang_ying"),
        ("系统", "xi_tong"),
        ("生效", "sheng_xiao"),
        ("帮助", "bang_zhu"),
        ("信息", "xin_xi"),
        ("显示", "xian_shi"),
        ("版本", "ban_ben"),
        ("压缩", "ya_suo"),
        ("触发", "chu_fa"),
        ("保留", "bao_liu"),
        ("上下文", "shang_xia_wen"),
        ("工具", "gong_ju"),
        ("调用", "diao_yong"),
        ("长", "chang"),
        ("对话", "dui_hua"),
        ("自动", "zi_dong"),
        ("清理", "qing_li"),
        ("历史", "li_shi"),
        ("需要", "xu_yao"),
        ("审批", "shen_pi"),
        ("安全", "an_quan"),
        ("危险", "wei_xian"),
        ("手动", "shou_dong"),
        ("失败", "shi_bai"),
        ("执行", "zhi_xing"),
        ("后", "hou"),
        ("继续", "ji_xu"),
        ("禁用", "jin_yong"),
        ("模式", "mo_shi"),
        ("超时", "chao_shi"),
        ("管道", "guan_dao"),
        ("命令", "ming_ling"),
        ("多重", "duo_zhong"),
        ("依赖", "yi_lai"),
        ("单个", "dan_ge"),
        ("多个", "duo_ge"),
        ("删除", "shan_chu"),
        ("文件", "wen_jian"),
        ("处理", "chu_li"),
        ("完整", "wan_zheng"),
        ("流式", "liu_shi"),
        ("空", "kong"),
        ("网络", "wang_luo"),
        ("错误", "cuo_wu"),
        ("配置", "pei_zhi"),
        ("优先级", "you_xian_ji"),
        ("环境变量", "huan_jing_bian_liang"),
        ("读写", "du_xie"),
        ("中断", "zhong_duan"),
        ("累积", "ji_lei"),
        ("文本", "wen_ben"),
        ("增量", "zeng_liang"),
        ("跟踪", "gen_zong"),
        ("计数", "ji_shu"),
        ("恢复", "hui_fu"),
        ("传输", "chuan_shu"),
        ("速率", "su_lv"),
        ("限制", "zhi_xian"),
        ("多段", "duo_duan"),
        ("段落", "duan_luo"),
        ("代码", "dai_ma"),
        ("块", "kuai"),
    ].iter().cloned().collect();

    let mut result = name.to_string();

    // 替换所有已知的中文字符
    for (chinese, pinyin) in &pinyin_map {
        result = result.replace(chinese, pinyin);
    }

    // 移除剩余的非 ASCII 字符
    let result: String = result.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else if c.is_whitespace() || c == '-' || c == '/' {
                '_'
            } else {
                '_'
            }
        })
        .collect();

    // 清理连续的下划线
    let result = result.split('_')
        .filter(|s| !s.is_empty())
        .collect::<Vec<&str>>()
        .join("_");

    // 如果结果为空或全是数字，添加前缀
    if result.is_empty() || result.chars().all(|c| c.is_numeric()) {
        let hash = name.chars().map(|c| c as u32).sum::<u32>();
        format!("test_{:x}", hash)
    } else {
        result
    }
}
