#!/bin/bash
# 🚀 IfAI CLI Homebrew 发布完整流程

set -e

# ========== 配置 ==========
CLI_NAME="ifai"
VERSION="${VERSION:-0.4.8}"  # 可通过环境变量覆盖
GITHUB_USER="${GITHUB_USER:-peterfei}"
GITHUB_REPO="${GITHUB_USER}/${CLI_NAME}"
TAP_REPO="${GITHUB_USER}/homebrew-ifai"

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }
log_success() { echo -e "${GREEN}✅ $1${NC}"; }
log_warn() { echo -e "${YELLOW}⚠️  $1${NC}"; }
log_error() { echo -e "${RED}❌ $1${NC}"; }

# ========== 步骤 1: 构建发布版本 ==========
log_info "步骤 1/6: 构建发布版本"

if [ ! -f "Cargo.toml" ]; then
    log_error "请在项目根目录运行此脚本"
    exit 1
fi

# 构建优化版本的二进制文件
log_info "构建 ${CLI_NAME} v${VERSION}..."
cargo build --release --bin "${CLI_NAME}"

if [ ! -f "target/release/${CLI_NAME}" ]; then
    log_error "构建失败"
    exit 1
fi

log_success "构建完成"

# ========== 步骤 2: 准备发布文件 ==========
log_info "步骤 2/6: 准备发布文件"

# 检测平台和架构
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"

if [ "${OS}" = "darwin" ]; then
  if [ "${ARCH}" = "arm64" ]; then
    TRIPLE="aarch64-apple-darwin"
  else
    TRIPLE="x86_64-apple-darwin"
  fi
else
  if [ "${ARCH}" = "aarch64" ]; then
    TRIPLE="aarch64-unknown-linux-gnu"
  else
    TRIPLE="x86_64-unknown-linux-gnu"
  fi
fi

RELEASE_FILE="${CLI_NAME}-${TRIPLE}"
GZ_FILE="${RELEASE_FILE}.gz"

# 创建压缩文件
log_info "创建压缩文件: ${GZ_FILE}"
gzip -c "target/release/${CLI_NAME}" > "${GZ_FILE}"

# 计算 SHA256
SHA256=$(shasum -a 256 "${GZ_FILE}" | awk '{print $1}')
log_success "SHA256: ${SHA256}"

# ========== 步骤 3: 创建 GitHub Release ==========
log_info "步骤 3/6: 创建 GitHub Release"

# 检查是否安装了 gh CLI
if ! command -v gh &> /dev/null; then
    log_warn "未安装 GitHub CLI，请手动创建 Release:"
    echo ""
    echo "  1. 访问: https://github.com/${GITHUB_REPO}/releases/new"
    echo "  2. 标签: v${VERSION}"
    echo "  3. 上传文件: ${GZ_FILE}"
    echo "  4. 发布说明见: release-notes.md"
    echo ""
    read -p "按 Enter 继续..."
else
  # 使用 gh CLI 创建 Release
  log_info "使用 GitHub CLI 创建 Release..."

  # 创建 Release Notes
  cat > /tmp/release-notes.md << EOF
## ${CLI_NAME} v${VERSION}

### 安装

\`\`\`bash
# 使用 Homebrew (推荐)
brew tap ${TAP_REPO}
brew install ${CLI_NAME}

# 或使用 Cargo
cargo install ${CLI_NAME} --version ${VERSION}
\`\`\`

### 更新内容

#### 新增
- 智能 Glob 搜索（防止上下文爆炸）
- 代码块流式渲染
- 元编程架构

#### 修复
- Glob 搜索路径匹配问题

---

### 校验和

| 平台 | SHA256 |
|------|--------|
| ${TRIPLE} | ${SHA256} |

### 系统要求

- macOS 12+ / Linux
- Rust 1.70+ (如果从源码构建)
EOF

  # 创建 Release（草稿模式）
  gh release create "v${VERSION}" \
    "${GZ_FILE}" \
    --notes-file /tmp/release-notes.md \
    --draft \
    --repo "${GITHUB_REPO}" || {
    log_warn "Release 创建可能失败，请手动检查"
  }

  log_success "Release 草稿已创建"
fi

# ========== 步骤 4: 生成 Homebrew Formula ==========
log_info "步骤 4/6: 生成 Homebrew Formula"

# 临时 Formula 目录
FORMULA_DIR="/tmp/homebrew-${CLI_NAME}"
mkdir -p "${FORMULA_DIR}/Formula"

# 生成 Formula
cat > "${FORMULA_DIR}/Formula/${CLI_NAME}.rb" << EOF
# typed: strict
# frozen_string_literal: true

# This file was generated by Homebrew.
# It is formatted with \`brew style\`.

class Ifai < Formula
  desc "AI-powered CLI with streaming code block rendering"
  homepage "https://github.com/${GITHUB_REPO}"
  version "${VERSION}"
  license "MIT"

  url "https://github.com/${GITHUB_REPO}/releases/download/v${VERSION}/${GZ_FILE}"
  sha256 "${SHA256}"

  def install
    bin.install "${CLI_NAME}"

    # 生成 shell 补全（可选）
    # bash_completion.install "completions/#{CLI_NAME}.bash" => "#{CLI_NAME}"
    # zsh_completion.install "completions/#{CLI_NAME}.zsh" => "_#{CLI_NAME}"
    # fish_completion.install "completions/#{CLI_NAME}.fish"
  end

  test do
    system "#{bin}/#{CLI_NAME}", "--version"
    system "#{bin}/#{CLI_NAME}", "help"
  end
end
EOF

log_success "Formula 已生成: ${FORMULA_DIR}/Formula/${CLI_NAME}.rb"

# ========== 步骤 5: 提交到 Tap 仓库 ==========
log_info "步骤 5/6: 提交到 Tap 仓库"

if [ -d "../homebrew-${CLI_NAME}" ]; then
    cd "../homebrew-${CLI_NAME}"
    git checkout main
    git pull

    # 复制 Formula
    cp "${FORMULA_DIR}/Formula/${CLI_NAME}.rb" "Formula/${CLI_NAME}.rb"

    # 提交
    git add "Formula/${CLI_NAME}.rb"
    git commit -m "🍺 ${CLI_NAME} ${VERSION}"
    git push

    log_success "已推送到 Tap: ${TAP_REPO}"
else
    log_warn "Tap 仓库不存在，请手动设置:"
    echo ""
    echo "  1. 克隆: git clone git@github.com:${TAP_REPO}.git ../homebrew-${CLI_NAME}"
    echo "  2. 复制 Formula: cp ${FORMULA_DIR}/Formula/${CLI_NAME}.rb ../homebrew-${CLI_NAME}/Formula/"
    echo "  3. 提交并推送"
    echo ""
fi

# ========== 步骤 6: 测试安装 ==========
log_info "步骤 6/6: 测试安装"

log_info "测试 brew install ..."
echo ""

# 测试命令（用户可以手动运行）
cat << EOF
# 测试安装（运行以下命令）：
brew tap ${TAP_REPO}
brew install ${CLI_NAME}
${CLI_NAME} --version

# 测试卸载：
brew uninstall ${CLI_NAME}
brew untap ${TAP_REPO}
EOF

log_success "🎉 发布流程完成！"
echo ""
log_info "总结："
echo "  1. ✅ 构建完成: target/release/${CLI_NAME}"
echo "  2. ✅ 发布文件: ${GZ_FILE}"
echo "  3. ✅ SHA256: ${SHA256}"
echo "  4. ✅ GitHub Release: v${VERSION}"
echo "  5. ✅ Homebrew Formula 已生成"
echo ""
log_info "用户安装命令:"
echo ""
echo "  brew tap ${TAP_REPO} && brew install ${CLI_NAME}"
echo ""
