#!/usr/bin/env ruby
# 🍺 自动生成 Homebrew Formula

require 'digest'

# 配置
CLI_NAME = "ifai"
VERSION = "0.4.3"
GITHUB_REPO = "your-username/ifai"  # 修改为实际仓库

# 平台配置
PLATFORMS = {
  "darwin" => {
    "x86_64" => "x86_64-apple-darwin",
    "arm64"  => "aarch64-apple-darwin"
  },
  "linux" => {
    "x86_64" => "x86_64-unknown-linux-gnu",
    "arm64"  => "aarch64-unknown-linux-gnu"
  }
}

# 生成 Formula 模板
def generate_formula(platform, arch, config)
  os_name = platform == "darwin" ? "macOS" : "Linux"
  triple = config[platform][arch]
  filename = "#{CLI_NAME}-#{triple}"

  <<~FORMULA
    # typed: strict
    # frozen_string_literal: true

    # This file was generated by Homebrew.
    # It is formatted with `brew style`.
    # To generate a new formula, run:
    #   ruby scripts/generate-homebrew-formula.rb

    class Ifai < Formula
      desc "AI-powered CLI with streaming code block rendering"
      homepage "https://github.com/#{GITHUB_REPO}"
      version "#{VERSION}"
      license "MIT"

      on_#{platform} do
        url "https://github.com/#{GITHUB_REPO}/releases/download/v#{VERSION}/#{filename}.gz"
        sha256 "#{fetch_sha256(filename)}"
      end

      def install
        bin.install "#{CLI_NAME}"
        bash_completion.install "completions/#{CLI_NAME}.bash" => "#{CLI_NAME}"
        zsh_completion.install "completions/#{CLI_NAME}.zsh" => "_#{CLI_NAME}"
        fish_completion.install "completions/#{CLI_NAME}.fish"
      end

      test do
        system "#{bin}/#{CLI_NAME}", "--version"
        system "#{bin}/#{CLI_NAME}", "help"
      end
    end
  FORMULA
end

# 获取 SHA256（需要先构建并上传文件）
def fetch_sha256(filename)
  # 实际使用时需要从 GitHub Release 获取文件并计算 SHA256
  # 这里返回占位符
  "SHA256_PLACEHOLDER"
end

# 生成所有平台的 Formula
puts "📝 生成 Homebrew Formula..."
puts ""

PLATFORMS.each do |platform, archs|
  archs.each do |arch, triple|
    formula = generate_formula(platform, arch, PLATFORMS)
    filename = "Formula/#{CLI_NAME}@#{triple}.rb"

    puts "生成: #{filename}"

    # 写入文件（实际使用时取消注释）
    # File.write(filename, formula)
    puts formula
    puts ""
    puts "=" * 80
    puts ""
  end
end

puts "✅ Formula 生成完成"
puts ""
puts "下一步："
puts "  1. 构建 release 二进制文件"
puts "  2. 上传到 GitHub Releases"
puts "  3. 计算实际 SHA256: shasum -a 256 ifai-*.gz"
puts "  4. 更新 Formula 中的 SHA256"
